import React from "react";
import styles from "../styles/Contact.module.scss";
import Head from "next/head";
import axios from "axios";
import { useState } from "react";

const Contact = () => {
  const formId = "f3MG0n1R";
  const formSparkUrl = `https://submit-form.com/${formId}`;

  const [submitting, setSubmitting] = useState(false);
  const [message, setMessage] = useState("");

  async function handleOnSubmit(e) {
    e.preventDefault();
    setSubmitting(true);
    const formData = {};

    Array.from(e.currentTarget.elements).forEach((field) => {
      if (!field.name) return;
      formData[field.name] = field.value;
    });

    const payload = {
      name: formData.name,
      email: formData.email,
      message: formData.message,
    };
    try {
      const result = await axios.post(formSparkUrl, payload);
      console.log(result);
      setMessage("Thanks, I will be in touch shortly.");
    } catch (error) {
      console.log(error);
      setMessage("Something went wrong, please try again.");
    }
    setSubmitting(false);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Contact Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.description}>Contact Form:</h3>
        <div className={styles.grid}>
          <style jsx>
            {`
              label {
                display: block;
                margin-bottom: 0.2em;
              }

              input {
                width: 100%;
              }

              textarea {
                height: auto;
                width: auto;
              }

              button {
                margin: auto;
                display: block;
              }
            `}
          </style>
          <form method="post" onSubmit={handleOnSubmit}>
            <p>
              <label htmlFor="name">Name/Company</label>
              <input type="text" name="name" required />
            </p>

            <p>
              <label htmlFor="email">Email</label>
              <input type="email" name="email" required />
            </p>

            <p>
              <label htmlFor="message">Message</label>
              <textarea rows="10" cols="45" name="message" required />
            </p>

            <p>
              <button
                disabled={submitting}
                className={styles.custombtn}
                type="submit"
              >
                {submitting ? "Submitting..." : "Submit"}
              </button>
            </p>
            <p className={styles.resultMsg}>{message}</p>
          </form>
        </div>
      </main>
    </div>
  );
};

export default Contact;
