/* eslint-disable @next/next/link-passhref */
import React from "react";
import styles from "../styles/Experience.module.scss";
import Head from "next/head";
import Image from "next/image";
import calculator from "../public/images/calculatorThumbnail.png";
import ethereum from "../public/images/ethereumThumbnail.png";
import landing from "../public/images/landingPageThumbnail.png";
import portfolio from "../public/images/portfolioThumbnail.png";
import Link from "next/link";

const Experience = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.expContainer}>
          <div className={styles.projectContainer}>
            <div className={(styles.project, styles.project1)}>
              <div className={styles.projectImage}>
                <a
                  href="https://shayanshadpour.github.io/react-calculator/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src={calculator}
                    alt="Picture of Calculator App"
                    layout="intrinsic"
                  />
                </a>
              </div>

              <div className={styles.projectTitle}>
                <h4>React Calculator </h4>
              </div>

              <div className={styles.projectDescription}>
                <p>Simple Calculator Application</p>
                <p className={styles.code}>React - HTML - CSS - JS</p>
              </div>
            </div>

            <div className={(styles.project, styles.project2)}>
              <div className={styles.projectImage}>
                <a
                  href="https://shayanshadpour.github.io/crypto-prices-chart/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src={ethereum}
                    alt="Picture of Crypto Tracking App"
                    layout="intrinsic"
                  />
                </a>
              </div>

              <div className={styles.projectTitle}>
                <h4>Ethereum Price Tracker</h4>
              </div>

              <div className={styles.projectDescription}>
                <p>Tracks and displays historical ETH prices</p>
                <p className={styles.code}>
                  React - HTML - SCSS - JS - ChartJS - Axios
                </p>
              </div>
            </div>

            <div className={(styles.project, styles.project3)}>
              <div className={styles.projectImage}>
                <a
                  href="https://shayanshadpour.github.io/frontend-mentor-landing-page/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Image
                    src={landing}
                    alt="Picture of Calculator App"
                    layout="intrinsic"
                  />
                </a>
              </div>

              <div className={styles.projectTitle}>
                <h4>Example Landing Page - Frontend Mentor</h4>
              </div>

              <div className={styles.projectDescription}>
                <p>Created website based on set of given designs</p>
                <p className={styles.code}>React - HTML - CSS - JS</p>
              </div>
            </div>

            <div className={(styles.project, styles.project4)}>
              <div className={styles.projectImage}>
                <Link href="/">
                  <Image
                    src={portfolio}
                    alt="Picture of Calculator App"
                    layout="intrinsic"
                  />
                </Link>
              </div>
              <div className={styles.projectTitle}>
                <h4>Portfolio Webpage</h4>
              </div>
              <div className={styles.projectDescription}>
                <p> Resume/Portfolio website</p>
                <p className={styles.code}>NextJS - HTML - CSS - JS - SCSS</p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Experience;
